### ISSUE TITLE
VSR Table View for Staff

### ISSUE THREAD

**Issue by benjaminJohnson2204** [TritonSE/PAP-Inventory-Processing#10]
Create the VSR table view page for staff to see a list of VSRs. Focus on the frontend at first, because the backend route for this task depends on the backend routes and DB models for other tasks being completed. 

### Frontend
- Implement the table view page. See [Figma design](https://www.figma.com/file/jARPdBWD6HutwLFzepjZW1/PAP-Web-Application?type=design&node-id=200-3694&mode=design&t=tO9klt7Btz8fMuUY-0).
- Put this page on the `/staff/vsr` URL
- I'd recommend using the [Material UI Table component](https://mui.com/material-ui/react-table/) for the table itself
- For now, focus on the UI of the page. That is, rendering the title, search bars, refresh & export buttons, and table view itself. Use some hard-coded dummy data in the table for now, and the buttons don't have to do anything yet.

### Backend
- Once our authentication backend routes and VSR database models are done, then we will need an API route to GET `/api/vsr/` that will return a list of all submitted VSRs. This route should require the user to be authenticated and have the `staff` or `admin` role. The frontend will then use this data to populate the VSRs table.
- The "Refresh" button should make the frontend make a new request to the backend to get the VSRs, and then update the table with the new data.
- Searching by keywords and filtering by status will eventually need to be implemented in this route

**Comment by Syu125** [comment]
Everything looks good! I just made a very minor change to get the font to show up for the two buttons.
